import libevdev

class Keyboard:
    pass

# jis keyboard
# {
#     EV_SYN:0: [
#         libevdev.EV_SYN.SYN_REPORT
#         libevdev.EV_SYN.SYN_CONFIG
#         libevdev.EV_SYN.SYN_MT_REPORT
#         libevdev.EV_SYN.SYN_DROPPED
#         libevdev.EV_SYN.SYN_04
#         libevdev.EV_SYN.SYN_05
#         libevdev.EV_SYN.SYN_06
#         libevdev.EV_SYN.SYN_07
#         libevdev.EV_SYN.SYN_08
#         libevdev.EV_SYN.SYN_09
#         libevdev.EV_SYN.SYN_0A
#         libevdev.EV_SYN.SYN_0B
#         libevdev.EV_SYN.SYN_0C
#         libevdev.EV_SYN.SYN_0D
#         libevdev.EV_SYN.SYN_0E
#         libevdev.EV_SYN.SYN_MAX
#     ],
#     EV_KEY:1: [
#        libevdev.EV_KEY.KEY_ESC
#        libevdev.EV_KEY.KEY_1
#        libevdev.EV_KEY.KEY_2
#        libevdev.EV_KEY.KEY_3
#        libevdev.EV_KEY.KEY_4
#        libevdev.EV_KEY.KEY_5
#        libevdev.EV_KEY.KEY_6
#        libevdev.EV_KEY.KEY_7
#        libevdev.EV_KEY.KEY_8
#        libevdev.EV_KEY.KEY_9
#        libevdev.EV_KEY.KEY_0
#        libevdev.EV_KEY.KEY_MINUS
#        libevdev.EV_KEY.KEY_EQUAL
#        libevdev.EV_KEY.KEY_BACKSPACE
#        libevdev.EV_KEY.KEY_TAB
#        libevdev.EV_KEY.KEY_Q
#        libevdev.EV_KEY.KEY_W
#        libevdev.EV_KEY.KEY_E
#        libevdev.EV_KEY.KEY_R
#        libevdev.EV_KEY.KEY_T
#        libevdev.EV_KEY.KEY_Y
#        libevdev.EV_KEY.KEY_U
#        libevdev.EV_KEY.KEY_I
#        libevdev.EV_KEY.KEY_O
#        libevdev.EV_KEY.KEY_P
#        libevdev.EV_KEY.KEY_LEFTBRACE
#        libevdev.EV_KEY.KEY_RIGHTBRACE
#        libevdev.EV_KEY.KEY_ENTER
#        libevdev.EV_KEY.KEY_LEFTCTRL
#        libevdev.EV_KEY.KEY_A
#        libevdev.EV_KEY.KEY_S
#        libevdev.EV_KEY.KEY_D
#        libevdev.EV_KEY.KEY_F
#        libevdev.EV_KEY.KEY_G
#        libevdev.EV_KEY.KEY_H
#        libevdev.EV_KEY.KEY_J
#        libevdev.EV_KEY.KEY_K
#        libevdev.EV_KEY.KEY_L
#        libevdev.EV_KEY.KEY_SEMICOLON
#        libevdev.EV_KEY.KEY_APOSTROPHE
#        libevdev.EV_KEY.KEY_GRAVE
#        libevdev.EV_KEY.KEY_LEFTSHIFT
#        libevdev.EV_KEY.KEY_BACKSLASH
#        libevdev.EV_KEY.KEY_Z
#        libevdev.EV_KEY.KEY_X
#        libevdev.EV_KEY.KEY_C
#        libevdev.EV_KEY.KEY_V
#        libevdev.EV_KEY.KEY_B
#        libevdev.EV_KEY.KEY_N
#        libevdev.EV_KEY.KEY_M
#        libevdev.EV_KEY.KEY_COMMA
#        libevdev.EV_KEY.KEY_DOT
#        libevdev.EV_KEY.KEY_SLASH
#        libevdev.EV_KEY.KEY_RIGHTSHIFT
#        libevdev.EV_KEY.KEY_KPASTERISK
#        libevdev.EV_KEY.KEY_LEFTALT
#        libevdev.EV_KEY.KEY_SPACE
#        libevdev.EV_KEY.KEY_CAPSLOCK
#        libevdev.EV_KEY.KEY_F1
#        libevdev.EV_KEY.KEY_F2
#        libevdev.EV_KEY.KEY_F3
#        libevdev.EV_KEY.KEY_F4
#        libevdev.EV_KEY.KEY_F5
#        libevdev.EV_KEY.KEY_F6
#        libevdev.EV_KEY.KEY_F7
#        libevdev.EV_KEY.KEY_F8
#        libevdev.EV_KEY.KEY_F9
#        libevdev.EV_KEY.KEY_F10
#        libevdev.EV_KEY.KEY_NUMLOCK
#        libevdev.EV_KEY.KEY_SCROLLLOCK
#        libevdev.EV_KEY.KEY_KP7
#        libevdev.EV_KEY.KEY_KP8
#        libevdev.EV_KEY.KEY_KP9
#        libevdev.EV_KEY.KEY_KPMINUS
#        libevdev.EV_KEY.KEY_KP4
#        libevdev.EV_KEY.KEY_KP5
#        libevdev.EV_KEY.KEY_KP6
#        libevdev.EV_KEY.KEY_KPPLUS
#        libevdev.EV_KEY.KEY_KP1
#        libevdev.EV_KEY.KEY_KP2
#        libevdev.EV_KEY.KEY_KP3
#        libevdev.EV_KEY.KEY_KP0
#        libevdev.EV_KEY.KEY_KPDOT
#        libevdev.EV_KEY.KEY_102ND
#        libevdev.EV_KEY.KEY_F11
#        libevdev.EV_KEY.KEY_F12
#        libevdev.EV_KEY.KEY_RO
#        libevdev.EV_KEY.KEY_HENKAN
#        libevdev.EV_KEY.KEY_KATAKANAHIRAGANA
#        libevdev.EV_KEY.KEY_MUHENKAN
#        libevdev.EV_KEY.KEY_KPJPCOMMA
#        libevdev.EV_KEY.KEY_KPENTER
#        libevdev.EV_KEY.KEY_RIGHTCTRL
#        libevdev.EV_KEY.KEY_KPSLASH
#        libevdev.EV_KEY.KEY_SYSRQ
#        libevdev.EV_KEY.KEY_RIGHTALT
#        libevdev.EV_KEY.KEY_HOME
#        libevdev.EV_KEY.KEY_UP
#        libevdev.EV_KEY.KEY_PAGEUP
#        libevdev.EV_KEY.KEY_LEFT
#        libevdev.EV_KEY.KEY_RIGHT
#        libevdev.EV_KEY.KEY_END
#        libevdev.EV_KEY.KEY_DOWN
#        libevdev.EV_KEY.KEY_PAGEDOWN
#        libevdev.EV_KEY.KEY_INSERT
#        libevdev.EV_KEY.KEY_DELETE
#        libevdev.EV_KEY.KEY_MUTE
#        libevdev.EV_KEY.KEY_VOLUMEDOWN
#        libevdev.EV_KEY.KEY_VOLUMEUP
#        libevdev.EV_KEY.KEY_POWER
#        libevdev.EV_KEY.KEY_KPEQUAL
#        libevdev.EV_KEY.KEY_PAUSE
#        libevdev.EV_KEY.KEY_KPCOMMA
#        libevdev.EV_KEY.KEY_HANGEUL
#        libevdev.EV_KEY.KEY_HANJA
#        libevdev.EV_KEY.KEY_YEN
#        libevdev.EV_KEY.KEY_LEFTMETA
#        libevdev.EV_KEY.KEY_RIGHTMETA
#        libevdev.EV_KEY.KEY_COMPOSE
#        libevdev.EV_KEY.KEY_STOP
#        libevdev.EV_KEY.KEY_AGAIN
#        libevdev.EV_KEY.KEY_PROPS
#        libevdev.EV_KEY.KEY_UNDO
#        libevdev.EV_KEY.KEY_FRONT
#        libevdev.EV_KEY.KEY_COPY
#        libevdev.EV_KEY.KEY_OPEN
#        libevdev.EV_KEY.KEY_PASTE
#        libevdev.EV_KEY.KEY_FIND
#        libevdev.EV_KEY.KEY_CUT
#        libevdev.EV_KEY.KEY_HELP
#        libevdev.EV_KEY.KEY_F13
#        libevdev.EV_KEY.KEY_F14
#        libevdev.EV_KEY.KEY_F15
#        libevdev.EV_KEY.KEY_F16
#        libevdev.EV_KEY.KEY_F17
#        libevdev.EV_KEY.KEY_F18
#        libevdev.EV_KEY.KEY_F19
#        libevdev.EV_KEY.KEY_F20
#        libevdev.EV_KEY.KEY_F21
#        libevdev.EV_KEY.KEY_F22
#        libevdev.EV_KEY.KEY_F23
#        libevdev.EV_KEY.KEY_F24
#        libevdev.EV_KEY.KEY_UNKNOWN
#     ],
#     EV_MSC:4: [
#         libevdev.EV_MSC.MSC_SCAN
#     ],
#     EV_LED:17: [
#         libevdev.EV_LED.LED_NUML
#         libevdev.EV_LED.LED_CAPSL
#         libevdev.EV_LED.LED_SCROLLL
#     ],
#     EV_REP:20: [
#         libevdev.EV_REP.REP_DELAY
#         libevdev.EV_REP.REP_PERIOD
#     ]
# }
